import { Inter } from "next/font/google";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/sass/app.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Auto Ai",
	description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
	return (
		<div>{children}</div>
	);
}

export default RootLayout