export const constants = {
	getGarage: '/garage',
	getAdmins: '/user/search/filter',
	getUsers: '/user',
	createGarage: '/garage',
	createAdmin: '/user',
	jobs: '/service_type',
	vehicle: '/vehicle',
	searchVehicle: '/vehicle/search/filter',
	searchCustomer: '/customer/search/filter',
	searchJob: '/service_type/search/filter',
	customer: '/customer',
	mechanic: '/userprofile',
	workOrder: '/workorders',
	mechanicByService: '/userprofile/search/service',
	job: '/job',
}